import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useContext } from "react";
import { NFTCollectionContext } from "@/contexts/NFTCollectionContext";
import NavBar from "@/components/NavBar";
import MintNft from "@/components/MintNft";

export default function Home() {
  const nftCollectionContext = useContext(NFTCollectionContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        {nftCollectionContext?.isLoading ? (
          <h1>Loading</h1>
        ) : !nftCollectionContext?.metamaskAccount ? (
          <button onClick={nftCollectionContext?.connectToWallet}>CONNECT TO WALLET</button>
        ) : (
          <>
            <NavBar />
            <MintNft />
          </>
        )}
      </main>
    </>
  );
}
